#! /usr/bin/env sh
cat > $fd/Output/A10.wpl << EOF
# A10: Unary not compile

int func program() {
  boolean b;
  b <- true;
  boolean b1;
  b1 <- ~b;
  boolean b2;
  b2 <- ~b1;
  int r <- 0;
  if (b) then {r <- r+1;}
  if (b1) then {r <- r+2;}
  if (b2) then {r <- r+4;}
  return r;
}
EOF
$fd/docompile A10 pass "A10: Unary not compile"