#! /usr/bin/env sh
cat > $fd/Output/C11.wpl << EOF
# C11: Arithmetic precedence 1
int func program() {
  int a;
  a <- 2;
  int b;
  b <- a + 20 * a;
  return b;
}
EOF
$fd/dorun C11 42 "C11: Arithmetic precedence 1"